# Role is generated by Rolify and helps manage user roles
class Role < ApplicationRecord
  has_many :users, through: :users_roles

  belongs_to :resource,
             polymorphic: true,
             optional: true

  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true
  scopify

  def self.non_permissions_roles
    Role.where.not(name: ['athlete', 'coach']).order('name ASC')
  end
end
