# Role is generated by Rolify and helps manage user roles
class Role < ApplicationRecord
  has_many :users, through: :users_roles

  belongs_to :resource,
             polymorphic: true,
             optional: true

  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true
  scopify

  def self.non_permissions_roles
    roles = Role.where(archived: false).order('name ASC')
    roles.reject { |r| r.name == 'athlete' || r.name == 'coach' }
  end

  def cap_name
    name.capitalize if name
  end
end
