# Role is generated by Rolify and helps manage user roles
class Role < ApplicationRecord
  # rubocop:disable Rails/HasManyOrHasOneDependent
  has_many :users, through: :users_roles
  # rubocop:enable Rails/HasManyOrHasOneDependent

  belongs_to :resource,
             polymorphic: true,
             optional: true

  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true
  scopify
end
